// js/data.js
// ============================================================
// HOW TO ADD A NEW PROJECT (no coding needed):
// 1. Create a new folder in /images, e.g. images/newplace/
// 2. Put a 4:3 thumbnail image in it named thumb.jpg
// 3. Put your full-size photos in it named 01.jpg, 02.jpg, 03.jpg...
// 4. Copy one of the blocks below, paste it into the PROJECTS array,
//    change the text and image list to match.
//    - "landscape" records whether a photo is wider than tall
//    - "thumbRatio" is the thumbnail's width divided by its height
//    - "thumb" is the full-quality thumbnail (used on the project page
//      as the lead image); "thumbGrid" is a smaller compressed copy of
//      the SAME photo used only on the homepage grid, so the grid loads
//      fast without permanently degrading the only copy of the photo.
//    All of the above are computed once from the files on disk, so the
//    page never has to download images just to check their shape. If
//    you add a photo/project and aren't sure of the exact numbers, a
//    rough guess is fine (landscape: true, thumbRatio: 1.5).
// 5. Save this file, refresh the browser. Done — no other file needs editing.
//
// The order of this array is the homepage order AND the order used by
// "Next project" on each project page (it wraps from the last back to the first).
// ============================================================

const PROJECTS = [
  {
    slug: "dolomites",
    title: "Dolomites",
    intro: "Write a short paragraph of body copy here — set the scene for this project, where it was shot and what it's about.",
    thumb: "images/dolomites/thumb.jpg",
    thumbGrid: "images/dolomites/thumb-grid.jpg",
    thumbRatio: 1.5004,
    images: [
      { src: "images/dolomites/01.jpg", caption: "Caption for photo 1", landscape: true },
      { src: "images/dolomites/02.jpg", caption: "Caption for photo 2", landscape: true },
      { src: "images/dolomites/03.jpg", caption: "Caption for photo 3", landscape: true },
      { src: "images/dolomites/04.jpg", caption: "Caption for photo 4", landscape: false },
      { src: "images/dolomites/05.jpg", caption: "Caption for photo 5", landscape: true },
      { src: "images/dolomites/07.jpg", caption: "Caption for photo 7", landscape: false },
      { src: "images/dolomites/08.jpg", caption: "Caption for photo 8", landscape: true },
      { src: "images/dolomites/10.jpg", caption: "Caption for photo 10", landscape: true },
      { src: "images/dolomites/11.jpg", caption: "Caption for photo 11", landscape: true },
      { src: "images/dolomites/12.jpg", caption: "Caption for photo 12", landscape: true },
      { src: "images/dolomites/13.jpg", caption: "Caption for photo 13", landscape: true },
      { src: "images/dolomites/15.jpg", caption: "Caption for photo 15", landscape: true },
      { src: "images/dolomites/16.jpg", caption: "Caption for photo 16", landscape: true },
      { src: "images/dolomites/17.jpg", caption: "Caption for photo 17", landscape: true },
      { src: "images/dolomites/18.jpg", caption: "Caption for photo 18", landscape: true },
      { src: "images/dolomites/19.jpg", caption: "Caption for photo 19", landscape: true },
      { src: "images/dolomites/20.jpg", caption: "Caption for photo 20", landscape: false },
      { src: "images/dolomites/21.jpg", caption: "Caption for photo 21", landscape: true },
      { src: "images/dolomites/22.jpg", caption: "Caption for photo 22", landscape: true },
      { src: "images/dolomites/23.jpg", caption: "Caption for photo 23", landscape: true },
      { src: "images/dolomites/24.jpg", caption: "Caption for photo 24", landscape: true },
      { src: "images/dolomites/25.jpg", caption: "Caption for photo 25", landscape: false },
      { src: "images/dolomites/26.jpg", caption: "Caption for photo 26", landscape: true }
    ]
  },
  {
    slug: "menorca",
    title: "Menorca",
    intro: "Write a short paragraph of body copy here — set the scene for this project, where it was shot and what it's about.",
    thumb: "images/menorca/thumb.jpg",
    thumbGrid: "images/menorca/thumb-grid.jpg",
    thumbRatio: 1.5004,
    images: [
      { src: "images/menorca/01.jpg", caption: "Caption for photo 1", landscape: true },
      { src: "images/menorca/02.jpg", caption: "Caption for photo 2", landscape: true },
      { src: "images/menorca/03.jpg", caption: "Caption for photo 3", landscape: true },
      { src: "images/menorca/04.jpg", caption: "Caption for photo 4", landscape: true },
      { src: "images/menorca/05.jpg", caption: "Caption for photo 5", landscape: true },
      { src: "images/menorca/06.jpg", caption: "Caption for photo 6", landscape: true },
      { src: "images/menorca/07.jpg", caption: "Caption for photo 7", landscape: true },
      { src: "images/menorca/08.jpg", caption: "Caption for photo 8", landscape: true },
      { src: "images/menorca/09.jpg", caption: "Caption for photo 9", landscape: true },
      { src: "images/menorca/10.jpg", caption: "Caption for photo 10", landscape: true },
      { src: "images/menorca/11.jpg", caption: "Caption for photo 11", landscape: true },
      { src: "images/menorca/12.jpg", caption: "Caption for photo 12", landscape: true },
      { src: "images/menorca/13.jpg", caption: "Caption for photo 13", landscape: true },
      { src: "images/menorca/14.jpg", caption: "Caption for photo 14", landscape: true },
      { src: "images/menorca/15.jpg", caption: "Caption for photo 15", landscape: false },
      { src: "images/menorca/16.jpg", caption: "Caption for photo 16", landscape: true },
      { src: "images/menorca/17.jpg", caption: "Caption for photo 17", landscape: true },
      { src: "images/menorca/18.jpg", caption: "Caption for photo 18", landscape: true },
      { src: "images/menorca/19.jpg", caption: "Caption for photo 19", landscape: true },
      { src: "images/menorca/20.jpg", caption: "Caption for photo 20", landscape: true },
      { src: "images/menorca/21.jpg", caption: "Caption for photo 21", landscape: true },
      { src: "images/menorca/22.jpg", caption: "Caption for photo 22", landscape: true },
      { src: "images/menorca/23.jpg", caption: "Caption for photo 23", landscape: false },
      { src: "images/menorca/24.jpg", caption: "Caption for photo 24", landscape: true },
      { src: "images/menorca/25.jpg", caption: "Caption for photo 25", landscape: true },
      { src: "images/menorca/26.jpg", caption: "Caption for photo 26", landscape: true },
      { src: "images/menorca/27.jpg", caption: "Caption for photo 27", landscape: true },
      { src: "images/menorca/28.jpg", caption: "Caption for photo 28", landscape: true },
      { src: "images/menorca/29.jpg", caption: "Caption for photo 29", landscape: true },
      { src: "images/menorca/30.jpg", caption: "Caption for photo 30", landscape: true },
      { src: "images/menorca/31.jpg", caption: "Caption for photo 31", landscape: true },
      { src: "images/menorca/32.jpg", caption: "Caption for photo 32", landscape: true },
      { src: "images/menorca/33.jpg", caption: "Caption for photo 33", landscape: true },
      { src: "images/menorca/34.jpg", caption: "Caption for photo 34", landscape: true },
      { src: "images/menorca/35.jpg", caption: "Caption for photo 35", landscape: true },
      { src: "images/menorca/36.jpg", caption: "Caption for photo 36", landscape: true },
      { src: "images/menorca/37.jpg", caption: "Caption for photo 37", landscape: false },
      { src: "images/menorca/38.jpg", caption: "Caption for photo 38", landscape: true },
      { src: "images/menorca/39.jpg", caption: "Caption for photo 39", landscape: true },
      { src: "images/menorca/40.jpg", caption: "Caption for photo 40", landscape: true },
      { src: "images/menorca/41.jpg", caption: "Caption for photo 41", landscape: false },
      { src: "images/menorca/42.jpg", caption: "Caption for photo 42", landscape: true },
      { src: "images/menorca/43.jpg", caption: "Caption for photo 43", landscape: false },
      { src: "images/menorca/44.jpg", caption: "Caption for photo 44", landscape: false },
      { src: "images/menorca/45.jpg", caption: "Caption for photo 45", landscape: true }
    ]
  },
  {
    slug: "slovenia",
    title: "Slovenia",
    intro: "Write a short paragraph of body copy here — set the scene for this project, where it was shot and what it's about.",
    thumb: "images/slovenia/thumb.jpg",
    thumbGrid: "images/slovenia/thumb-grid.jpg",
    thumbRatio: 1.5004,
    images: [
      { src: "images/slovenia/01.jpg", caption: "Caption for photo 1", landscape: true },
      { src: "images/slovenia/02.jpg", caption: "Caption for photo 2", landscape: true },
      { src: "images/slovenia/03.jpg", caption: "Caption for photo 3", landscape: true },
      { src: "images/slovenia/04.jpg", caption: "Caption for photo 4", landscape: true },
      { src: "images/slovenia/05.jpg", caption: "Caption for photo 5", landscape: true },
      { src: "images/slovenia/06.jpg", caption: "Caption for photo 6", landscape: false },
      { src: "images/slovenia/07.jpg", caption: "Caption for photo 7", landscape: true },
      { src: "images/slovenia/08.jpg", caption: "Caption for photo 8", landscape: true },
      { src: "images/slovenia/09.jpg", caption: "Caption for photo 9", landscape: true },
      { src: "images/slovenia/10.jpg", caption: "Caption for photo 10", landscape: true },
      { src: "images/slovenia/11.jpg", caption: "Caption for photo 11", landscape: true },
      { src: "images/slovenia/12.jpg", caption: "Caption for photo 12", landscape: true },
      { src: "images/slovenia/13.jpg", caption: "Caption for photo 13", landscape: true }
    ]
  },
  {
    slug: "fam",
    title: "Fam",
    intro: "Write a short paragraph of body copy here — set the scene for this project, where it was shot and what it's about.",
    thumb: "images/fam/thumb.jpg",
    thumbGrid: "images/fam/thumb-grid.jpg",
    thumbRatio: 1.4925,
    images: [
      { src: "images/fam/01.jpg", caption: "Caption for photo 1", landscape: true },
      { src: "images/fam/02.jpg", caption: "Caption for photo 2", landscape: true },
      { src: "images/fam/03.jpg", caption: "Caption for photo 3", landscape: true },
      { src: "images/fam/04.jpg", caption: "Caption for photo 4", landscape: true },
      { src: "images/fam/05.jpg", caption: "Caption for photo 5", landscape: true },
      { src: "images/fam/06.jpg", caption: "Caption for photo 6", landscape: true },
      { src: "images/fam/07.jpg", caption: "Caption for photo 7", landscape: true },
      { src: "images/fam/08.jpg", caption: "Caption for photo 8", landscape: true }
    ]
  },
  {
    slug: "allie",
    title: "Per Molts d'anys, Allie!",
    intro: "Write a short paragraph of body copy here — set the scene for this project, where it was shot and what it's about.",
    thumb: "images/allie/thumb.jpg",
    thumbGrid: "images/allie/thumb-grid.jpg",
    thumbRatio: 1.5004,
    images: [
      { src: "images/allie/01.jpg", caption: "Caption for photo 1", landscape: true },
      { src: "images/allie/02.jpg", caption: "Caption for photo 2", landscape: true },
      { src: "images/allie/03.jpg", caption: "Caption for photo 3", landscape: true },
      { src: "images/allie/04.jpg", caption: "Caption for photo 4", landscape: true },
      { src: "images/allie/05.jpg", caption: "Caption for photo 5", landscape: true },
      { src: "images/allie/06.jpg", caption: "Caption for photo 6", landscape: true },
      { src: "images/allie/07.jpg", caption: "Caption for photo 7", landscape: true },
      { src: "images/allie/08.jpg", caption: "Caption for photo 8", landscape: true },
      { src: "images/allie/09.jpg", caption: "Caption for photo 9", landscape: true },
      { src: "images/allie/10.jpg", caption: "Caption for photo 10", landscape: true },
      { src: "images/allie/11.jpg", caption: "Caption for photo 11", landscape: true },
      { src: "images/allie/12.jpg", caption: "Caption for photo 12", landscape: true },
      { src: "images/allie/13.jpg", caption: "Caption for photo 13", landscape: true },
      { src: "images/allie/14.jpg", caption: "Caption for photo 14", landscape: true },
      { src: "images/allie/15.jpg", caption: "Caption for photo 15", landscape: true },
      { src: "images/allie/16.jpg", caption: "Caption for photo 16", landscape: true },
      { src: "images/allie/17.jpg", caption: "Caption for photo 17", landscape: true },
      { src: "images/allie/18.jpg", caption: "Caption for photo 18", landscape: true },
      { src: "images/allie/19.jpg", caption: "Caption for photo 19", landscape: true },
      { src: "images/allie/20.jpg", caption: "Caption for photo 20", landscape: true },
      { src: "images/allie/21.jpg", caption: "Caption for photo 21", landscape: true },
      { src: "images/allie/22.jpg", caption: "Caption for photo 22", landscape: true },
      { src: "images/allie/23.jpg", caption: "Caption for photo 23", landscape: true },
      { src: "images/allie/24.jpg", caption: "Caption for photo 24", landscape: true },
      { src: "images/allie/25.jpg", caption: "Caption for photo 25", landscape: true },
      { src: "images/allie/26.jpg", caption: "Caption for photo 26", landscape: true }
    ]
  },
  {
    slug: "basilicacistern",
    title: "Basilica Cistern",
    intro: "Write a short paragraph of body copy here — set the scene for this project, where it was shot and what it's about.",
    thumb: "images/basilicacistern/thumb.jpg",
    thumbGrid: "images/basilicacistern/thumb-grid.jpg",
    thumbRatio: 1.5004,
    images: [
      { src: "images/basilicacistern/01.jpg", caption: "Caption for photo 1", landscape: true },
      { src: "images/basilicacistern/02.jpg", caption: "Caption for photo 2", landscape: false },
      { src: "images/basilicacistern/03.jpg", caption: "Caption for photo 3", landscape: true },
      { src: "images/basilicacistern/05.jpg", caption: "Caption for photo 5", landscape: false },
      { src: "images/basilicacistern/06.jpg", caption: "Caption for photo 6", landscape: false },
      { src: "images/basilicacistern/07.jpg", caption: "Caption for photo 7", landscape: true },
      { src: "images/basilicacistern/08.jpg", caption: "Caption for photo 8", landscape: true }
    ]
  },
  {
    slug: "cheesemongers",
    title: "Cheesemongers",
    intro: "Write a short paragraph of body copy here — set the scene for this project, where it was shot and what it's about.",
    thumb: "images/cheesemongers/thumb.jpg",
    thumbGrid: "images/cheesemongers/thumb-grid.jpg",
    thumbRatio: 1.5004,
    images: [
      { src: "images/cheesemongers/01.jpg", caption: "Caption for photo 1", landscape: true },
      { src: "images/cheesemongers/02.jpg", caption: "Caption for photo 2", landscape: true },
      { src: "images/cheesemongers/03.jpg", caption: "Caption for photo 3", landscape: false },
      { src: "images/cheesemongers/04.jpg", caption: "Caption for photo 4", landscape: true },
      { src: "images/cheesemongers/05.jpg", caption: "Caption for photo 5", landscape: false },
      { src: "images/cheesemongers/07.jpg", caption: "Caption for photo 7", landscape: true },
      { src: "images/cheesemongers/08.jpg", caption: "Caption for photo 8", landscape: false },
      { src: "images/cheesemongers/09.jpg", caption: "Caption for photo 9", landscape: false },
      { src: "images/cheesemongers/10.jpg", caption: "Caption for photo 10", landscape: true },
      { src: "images/cheesemongers/11.jpg", caption: "Caption for photo 11", landscape: false },
      { src: "images/cheesemongers/12.jpg", caption: "Caption for photo 12", landscape: true },
      { src: "images/cheesemongers/13.jpg", caption: "Caption for photo 13", landscape: true }
    ]
  },
  {
    slug: "lonnie",
    title: "Lonnie",
    intro: "Write a short paragraph of body copy here — set the scene for this project, where it was shot and what it's about.",
    thumb: "images/lonnie/thumb.jpg",
    thumbGrid: "images/lonnie/thumb-grid.jpg",
    thumbRatio: 1.4925,
    images: [
      { src: "images/lonnie/01.jpg", caption: "Caption for photo 1", landscape: true },
      { src: "images/lonnie/02.jpg", caption: "Caption for photo 2", landscape: true },
      { src: "images/lonnie/03.jpg", caption: "Caption for photo 3", landscape: true },
      { src: "images/lonnie/04.jpg", caption: "Caption for photo 4", landscape: true },
      { src: "images/lonnie/05.jpg", caption: "Caption for photo 5", landscape: true },
      { src: "images/lonnie/06.jpg", caption: "Caption for photo 6", landscape: true },
      { src: "images/lonnie/07.jpg", caption: "Caption for photo 7", landscape: true },
      { src: "images/lonnie/08.jpg", caption: "Caption for photo 8", landscape: true },
      { src: "images/lonnie/09.jpg", caption: "Caption for photo 9", landscape: true },
      { src: "images/lonnie/10.jpg", caption: "Caption for photo 10", landscape: true },
      { src: "images/lonnie/11.jpg", caption: "Caption for photo 11", landscape: true },
      { src: "images/lonnie/12.jpg", caption: "Caption for photo 12", landscape: true },
      { src: "images/lonnie/13.jpg", caption: "Caption for photo 13", landscape: true },
      { src: "images/lonnie/14.jpg", caption: "Caption for photo 14", landscape: true },
      { src: "images/lonnie/15.jpg", caption: "Caption for photo 15", landscape: true },
      { src: "images/lonnie/16.jpg", caption: "Caption for photo 16", landscape: true },
      { src: "images/lonnie/17.jpg", caption: "Caption for photo 17", landscape: true },
      { src: "images/lonnie/18.jpg", caption: "Caption for photo 18", landscape: true },
      { src: "images/lonnie/19.jpg", caption: "Caption for photo 19", landscape: true },
      { src: "images/lonnie/20.jpg", caption: "Caption for photo 20", landscape: true },
      { src: "images/lonnie/21.jpg", caption: "Caption for photo 21", landscape: true }
    ]
  },
  {
    slug: "darkmofo",
    title: "Dark Mofo",
    intro: "Write a short paragraph of body copy here — set the scene for this project, where it was shot and what it's about.",
    thumb: "images/darkmofo/thumb.jpg",
    thumbGrid: "images/darkmofo/thumb-grid.jpg",
    thumbRatio: 1.4981,
    images: [
      { src: "images/darkmofo/01.jpg", caption: "Caption for photo 1", landscape: true },
      { src: "images/darkmofo/02.jpg", caption: "Caption for photo 2", landscape: true },
      { src: "images/darkmofo/03.jpg", caption: "Caption for photo 3", landscape: true },
      { src: "images/darkmofo/04.jpg", caption: "Caption for photo 4", landscape: true },
      { src: "images/darkmofo/05.jpg", caption: "Caption for photo 5", landscape: true },
      { src: "images/darkmofo/06.jpg", caption: "Caption for photo 6", landscape: true },
      { src: "images/darkmofo/07.jpg", caption: "Caption for photo 7", landscape: true },
      { src: "images/darkmofo/08.jpg", caption: "Caption for photo 8", landscape: true },
      { src: "images/darkmofo/09.jpg", caption: "Caption for photo 9", landscape: true },
      { src: "images/darkmofo/10.jpg", caption: "Caption for photo 10", landscape: true },
      { src: "images/darkmofo/11.jpg", caption: "Caption for photo 11", landscape: true },
      { src: "images/darkmofo/12.jpg", caption: "Caption for photo 12", landscape: true },
      { src: "images/darkmofo/13.jpg", caption: "Caption for photo 13", landscape: true },
      { src: "images/darkmofo/14.jpg", caption: "Caption for photo 14", landscape: true },
      { src: "images/darkmofo/15.jpg", caption: "Caption for photo 15", landscape: true },
      { src: "images/darkmofo/16.jpg", caption: "Caption for photo 16", landscape: true },
      { src: "images/darkmofo/17.jpg", caption: "Caption for photo 17", landscape: true },
      { src: "images/darkmofo/18.jpg", caption: "Caption for photo 18", landscape: true },
      { src: "images/darkmofo/19.jpg", caption: "Caption for photo 19", landscape: true },
      { src: "images/darkmofo/20.jpg", caption: "Caption for photo 20", landscape: true },
      { src: "images/darkmofo/21.jpg", caption: "Caption for photo 21", landscape: true },
      { src: "images/darkmofo/22.jpg", caption: "Caption for photo 22", landscape: true },
      { src: "images/darkmofo/23.jpg", caption: "Caption for photo 23", landscape: true },
      { src: "images/darkmofo/24.jpg", caption: "Caption for photo 24", landscape: true },
      { src: "images/darkmofo/25.jpg", caption: "Caption for photo 25", landscape: true },
      { src: "images/darkmofo/26.jpg", caption: "Caption for photo 26", landscape: true },
      { src: "images/darkmofo/27.jpg", caption: "Caption for photo 27", landscape: true },
      { src: "images/darkmofo/28.jpg", caption: "Caption for photo 28", landscape: true },
      { src: "images/darkmofo/29.jpg", caption: "Caption for photo 29", landscape: true },
      { src: "images/darkmofo/30.jpg", caption: "Caption for photo 30", landscape: true },
      { src: "images/darkmofo/31.jpg", caption: "Caption for photo 31", landscape: true }
    ]
  },
  {
    slug: "thecatlins",
    title: "The Catlins",
    intro: "Write a short paragraph of body copy here — set the scene for this project, where it was shot and what it's about.",
    thumb: "images/thecatlins/thumb.jpg",
    thumbGrid: "images/thecatlins/thumb-grid.jpg",
    thumbRatio: 1.5004,
    images: [
      { src: "images/thecatlins/04.jpg", caption: "Caption for photo 4", landscape: true },
      { src: "images/thecatlins/05.jpg", caption: "Caption for photo 5", landscape: false },
      { src: "images/thecatlins/06.jpg", caption: "Caption for photo 6", landscape: true },
      { src: "images/thecatlins/07.jpg", caption: "Caption for photo 7", landscape: true },
      { src: "images/thecatlins/08.jpg", caption: "Caption for photo 8", landscape: true },
      { src: "images/thecatlins/09.jpg", caption: "Caption for photo 9", landscape: true },
      { src: "images/thecatlins/10.jpg", caption: "Caption for photo 10", landscape: true },
      { src: "images/thecatlins/11.jpg", caption: "Caption for photo 11", landscape: true },
      { src: "images/thecatlins/13.jpg", caption: "Caption for photo 13", landscape: true },
      { src: "images/thecatlins/14.jpg", caption: "Caption for photo 14", landscape: false },
      { src: "images/thecatlins/15.jpg", caption: "Caption for photo 15", landscape: true },
      { src: "images/thecatlins/16.jpg", caption: "Caption for photo 16", landscape: true },
      { src: "images/thecatlins/17.jpg", caption: "Caption for photo 17", landscape: true },
      { src: "images/thecatlins/18.jpg", caption: "Caption for photo 18", landscape: true },
      { src: "images/thecatlins/19.jpg", caption: "Caption for photo 19", landscape: true },
      { src: "images/thecatlins/20.jpg", caption: "Caption for photo 20", landscape: true },
      { src: "images/thecatlins/21.jpg", caption: "Caption for photo 21", landscape: true },
      { src: "images/thecatlins/22.jpg", caption: "Caption for photo 22", landscape: true },
      { src: "images/thecatlins/23.jpg", caption: "Caption for photo 23", landscape: true },
      { src: "images/thecatlins/24.jpg", caption: "Caption for photo 24", landscape: true },
      { src: "images/thecatlins/25.jpg", caption: "Caption for photo 25", landscape: true },
      { src: "images/thecatlins/26.jpg", caption: "Caption for photo 26", landscape: true },
      { src: "images/thecatlins/27.jpg", caption: "Caption for photo 27", landscape: true },
      { src: "images/thecatlins/30.jpg", caption: "Caption for photo 30", landscape: true },
      { src: "images/thecatlins/31.jpg", caption: "Caption for photo 31", landscape: true }
    ]
  },
  {
    slug: "foxriver",
    title: "Fox River",
    intro: "Write a short paragraph of body copy here — set the scene for this project, where it was shot and what it's about.",
    thumb: "images/foxriver/thumb.jpg",
    thumbGrid: "images/foxriver/thumb-grid.jpg",
    thumbRatio: 1.4925,
    images: [
      { src: "images/foxriver/01.jpg", caption: "Caption for photo 1", landscape: true },
      { src: "images/foxriver/02.jpg", caption: "Caption for photo 2", landscape: true },
      { src: "images/foxriver/03.jpg", caption: "Caption for photo 3", landscape: true },
      { src: "images/foxriver/04.jpg", caption: "Caption for photo 4", landscape: true },
      { src: "images/foxriver/05.jpg", caption: "Caption for photo 5", landscape: true },
      { src: "images/foxriver/06.jpg", caption: "Caption for photo 6", landscape: true },
      { src: "images/foxriver/07.jpg", caption: "Caption for photo 7", landscape: true },
      { src: "images/foxriver/08.jpg", caption: "Caption for photo 8", landscape: true },
      { src: "images/foxriver/09.jpg", caption: "Caption for photo 9", landscape: true },
      { src: "images/foxriver/10.jpg", caption: "Caption for photo 10", landscape: true },
      { src: "images/foxriver/11.jpg", caption: "Caption for photo 11", landscape: true },
      { src: "images/foxriver/12.jpg", caption: "Caption for photo 12", landscape: true },
      { src: "images/foxriver/13.jpg", caption: "Caption for photo 13", landscape: false },
      { src: "images/foxriver/14.jpg", caption: "Caption for photo 14", landscape: true },
      { src: "images/foxriver/15.jpg", caption: "Caption for photo 15", landscape: true },
      { src: "images/foxriver/16.jpg", caption: "Caption for photo 16", landscape: true },
      { src: "images/foxriver/17.jpg", caption: "Caption for photo 17", landscape: true },
      { src: "images/foxriver/18.jpg", caption: "Caption for photo 18", landscape: true }
    ]
  },
  {
    slug: "southisland",
    title: "South Island",
    intro: "Write a short paragraph of body copy here — set the scene for this project, where it was shot and what it's about.",
    thumb: "images/southisland/thumb.jpg",
    thumbGrid: "images/southisland/thumb-grid.jpg",
    thumbRatio: 1.4914,
    images: [
      { src: "images/southisland/01.jpg", caption: "Caption for photo 1", landscape: true },
      { src: "images/southisland/02.jpg", caption: "Caption for photo 2", landscape: true },
      { src: "images/southisland/03.jpg", caption: "Caption for photo 3", landscape: true },
      { src: "images/southisland/04.jpg", caption: "Caption for photo 4", landscape: true },
      { src: "images/southisland/05.jpg", caption: "Caption for photo 5", landscape: true },
      { src: "images/southisland/06.jpg", caption: "Caption for photo 6", landscape: true },
      { src: "images/southisland/07.jpg", caption: "Caption for photo 7", landscape: true },
      { src: "images/southisland/08.jpg", caption: "Caption for photo 8", landscape: true },
      { src: "images/southisland/09.jpg", caption: "Caption for photo 9", landscape: true },
      { src: "images/southisland/10.jpg", caption: "Caption for photo 10", landscape: true },
      { src: "images/southisland/11.jpg", caption: "Caption for photo 11", landscape: true },
      { src: "images/southisland/12.jpg", caption: "Caption for photo 12", landscape: true },
      { src: "images/southisland/13.jpg", caption: "Caption for photo 13", landscape: true },
      { src: "images/southisland/14.jpg", caption: "Caption for photo 14", landscape: true },
      { src: "images/southisland/15.jpg", caption: "Caption for photo 15", landscape: true },
      { src: "images/southisland/16.jpg", caption: "Caption for photo 16", landscape: true },
      { src: "images/southisland/17.jpg", caption: "Caption for photo 17", landscape: true },
      { src: "images/southisland/18.jpg", caption: "Caption for photo 18", landscape: true },
      { src: "images/southisland/19.jpg", caption: "Caption for photo 19", landscape: true },
      { src: "images/southisland/20.jpg", caption: "Caption for photo 20", landscape: true },
      { src: "images/southisland/21.jpg", caption: "Caption for photo 21", landscape: true },
      { src: "images/southisland/22.jpg", caption: "Caption for photo 22", landscape: true },
      { src: "images/southisland/23.jpg", caption: "Caption for photo 23", landscape: true },
      { src: "images/southisland/24.jpg", caption: "Caption for photo 24", landscape: true },
      { src: "images/southisland/25.jpg", caption: "Caption for photo 25", landscape: true },
      { src: "images/southisland/26.jpg", caption: "Caption for photo 26", landscape: true },
      { src: "images/southisland/27.jpg", caption: "Caption for photo 27", landscape: true },
      { src: "images/southisland/28.jpg", caption: "Caption for photo 28", landscape: true },
      { src: "images/southisland/29.jpg", caption: "Caption for photo 29", landscape: true }
    ]
  }
];
